#include "spu_test.spu.h"

int main(void)
{		
	TEST_2_vl(spu_slqwbyte, vec_float4_t, uint32_t, vec_float4_t)
	TEST_2_vl(spu_slqwbyte, vec_double2_t, uint32_t, vec_double2_t)
	TEST_2_vl(spu_slqwbytebc, vec_llong2_t, uint32_t, vec_llong2_t)
	TEST_2_vl(spu_slqwbytebc, vec_ullong2_t, uint32_t, vec_ullong2_t)
	TEST_2_vl(spu_slqwbytebc, vec_int4_t, uint32_t, vec_int4_t)
	TEST_2_vl(spu_slqwbytebc, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_slqwbytebc, vec_short8_t, uint32_t, vec_short8_t)
	TEST_2_vl(spu_slqwbytebc, vec_ushort8_t, uint32_t, vec_ushort8_t)
	TEST_2_vl(spu_slqwbytebc, vec_char16_t, uint32_t, vec_char16_t)
	TEST_2_vl(spu_slqwbytebc, vec_uchar16_t, uint32_t, vec_uchar16_t)
	TEST_2_vl(spu_slqwbytebc, vec_float4_t, uint32_t, vec_float4_t)
	TEST_2_vl(spu_slqwbytebc, vec_double2_t, uint32_t, vec_double2_t)
	TEST_1_l(spu_splats, uint8_t, vec_uchar16_t)
	TEST_1_l(spu_splats, int8_t, vec_char16_t)
	TEST_1_l(spu_splats, char, vec_char16_t)
	TEST_1_l(spu_splats, uint16_t, vec_ushort8_t)
	TEST_1_l(spu_splats, int16_t, vec_short8_t)
	TEST_1_l(spu_splats, uint32_t, vec_uint4_t)
	TEST_1_l(spu_splats, int32_t, vec_int4_t)
	TEST_1_l(spu_splats, uint64_t, vec_ullong2_t)
	TEST_1_l(spu_splats, int64_t, vec_llong2_t)
	TEST_2_vl(spu_extract, vec_uchar16_t, int32_t, uint8_t)
	TEST_2_vl(spu_extract, vec_char16_t, int32_t, int8_t)
	TEST_2_vl(spu_extract, vec_ushort8_t, int32_t, uint16_t)
	TEST_2_vl(spu_extract, vec_short8_t, int32_t, int16_t)
	TEST_2_vl(spu_extract, vec_uint4_t, int32_t, uint32_t)
	TEST_2_vl(spu_extract, vec_int4_t, int32_t, int32_t)
	TEST_2_vl(spu_extract, vec_ullong2_t, int32_t, uint64_t)
	TEST_2_vl(spu_extract, vec_llong2_t, int32_t, int64_t)
	TEST_2_vl(spu_extract, vec_float4_t, int32_t, float)
	TEST_2_vl(spu_extract, vec_double2_t, int32_t, double)
	TEST_3_vvl(spu_insert, uint8_t, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_3_vvl(spu_insert, int8_t, vec_char16_t, int32_t, vec_char16_t)
	TEST_3_vvl(spu_insert, uint16_t, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_3_vvl(spu_insert, int16_t, vec_short8_t, int32_t, vec_short8_t)
	TEST_3_vvl(spu_insert, uint32_t, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_3_vvl(spu_insert, int32_t, vec_int4_t, int32_t, vec_int4_t)
	TEST_3_vvl(spu_insert, uint64_t, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_3_vvl(spu_insert, int64_t, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_3_vvl(spu_insert, float, vec_float4_t, int32_t, vec_float4_t)
	TEST_3_vvl(spu_insert, double, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_promote, uint8_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_promote, int8_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_promote, char, int32_t, vec_char16_t)
	TEST_2_vl(spu_promote, uint16_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_promote, int16_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_promote, uint32_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_promote, int32_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_promote, uint64_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_promote, int64_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_promote, float, int32_t, vec_float4_t)
	TEST_2_vl(spu_promote, double, int32_t, vec_double2_t)
	TEST_2_vl_6(spu_convts, vec_float4_t, uint32_t, vec_int4_t)
	TEST_2_vl_6(spu_convtu, vec_float4_t, uint32_t, vec_uint4_t)
	
	return 0;
}
