#include "spu_test.spu.h"

int main(void)
{		
	TEST_2_vl(spu_or, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_or, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_xor, vec_uchar16_t, uint8_t, vec_uchar16_t)
	TEST_2_vl(spu_xor, vec_char16_t, int8_t, vec_char16_t)
	TEST_2_vl(spu_xor, vec_ushort8_t, uint16_t, vec_ushort8_t)
	TEST_2_vl(spu_xor, vec_short8_t, int16_t, vec_short8_t)
	TEST_2_vl(spu_xor, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_xor, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rl, vec_ushort8_t, int16_t, vec_ushort8_t)
	TEST_2_vl(spu_rl, vec_short8_t, int16_t, vec_short8_t)
	TEST_2_vl(spu_rl, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rl, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlqw, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_rlqw, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlqw, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlqw, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlqw, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlqw, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlqw, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlqw, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlqw, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlqw, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_rlqwbyte, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_rlqwbyte, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlqwbyte, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlqwbyte, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlqwbyte, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlqwbyte, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlqwbyte, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlqwbyte, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlqwbyte, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlqwbyte, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_rlqwbytebc, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_rlqwbytebc, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlqwbytebc, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlqwbytebc, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlqwbytebc, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlqwbytebc, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlqwbytebc, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlqwbytebc, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlqwbytebc, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlqwbytebc, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_rlmask, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlmask, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlmask, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlmask, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlmaska, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlmaska, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlmaska, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlmaska, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlmaskqw, vec_uchar16_t, int32_t, vec_uchar16_t)
	
	return 0;
}
