#include "spu_test.spu.h"

int main(void)
{		
	TEST_2_vl(spu_rlmaskqw, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlmaskqw, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlmaskqw, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlmaskqw, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlmaskqw, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlmaskqw, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlmaskqw, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlmaskqw, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlmaskqw, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlmaskqwbyte, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_uchar16_t, int32_t, vec_uchar16_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_char16_t, int32_t, vec_char16_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_ushort8_t, int32_t, vec_ushort8_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_short8_t, int32_t, vec_short8_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_uint4_t, int32_t, vec_uint4_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_int4_t, int32_t, vec_int4_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_ullong2_t, int32_t, vec_ullong2_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_llong2_t, int32_t, vec_llong2_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_float4_t, int32_t, vec_float4_t)
	TEST_2_vl(spu_rlmaskqwbytebc, vec_double2_t, int32_t, vec_double2_t)
	TEST_2_vl(spu_sl, vec_ushort8_t, uint32_t, vec_ushort8_t)
	TEST_2_vl(spu_sl, vec_short8_t, uint32_t, vec_short8_t)
	TEST_2_vl(spu_sl, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_sl, vec_int4_t, uint32_t, vec_int4_t)
	TEST_2_vl(spu_slqw, vec_llong2_t, uint32_t, vec_llong2_t)
	TEST_2_vl(spu_slqw, vec_ullong2_t, uint32_t, vec_ullong2_t)
	TEST_2_vl(spu_slqw, vec_int4_t, uint32_t, vec_int4_t)
	TEST_2_vl(spu_slqw, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_slqw, vec_short8_t, uint32_t, vec_short8_t)
	TEST_2_vl(spu_slqw, vec_ushort8_t, uint32_t, vec_ushort8_t)
	TEST_2_vl(spu_slqw, vec_char16_t, uint32_t, vec_char16_t)
	TEST_2_vl(spu_slqw, vec_uchar16_t, uint32_t, vec_uchar16_t)
	TEST_2_vl(spu_slqw, vec_float4_t, uint32_t, vec_float4_t)
	TEST_2_vl(spu_slqw, vec_double2_t, uint32_t, vec_double2_t)
	TEST_2_vl(spu_slqwbyte, vec_llong2_t, uint32_t, vec_llong2_t)
	TEST_2_vl(spu_slqwbyte, vec_ullong2_t, uint32_t, vec_ullong2_t)
	TEST_2_vl(spu_slqwbyte, vec_int4_t, uint32_t, vec_int4_t)
	TEST_2_vl(spu_slqwbyte, vec_uint4_t, uint32_t, vec_uint4_t)
	TEST_2_vl(spu_slqwbyte, vec_short8_t, uint32_t, vec_short8_t)
	TEST_2_vl(spu_slqwbyte, vec_ushort8_t, uint32_t, vec_ushort8_t)
	TEST_2_vl(spu_slqwbyte, vec_char16_t, uint32_t, vec_char16_t)
	TEST_2_vl(spu_slqwbyte, vec_uchar16_t, uint32_t, vec_uchar16_t)
	
	return 0;
}
